---
apiVersion: batch/v1
kind: apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
  labels:
    type: oneshot
spec:
  template:
    spec:
      containers:
      - name: job
        image: alpine
        command: ["sleep",  "30s"]
      restartPolicy: OnFailure